name: Docker 
on:
 workflow_call

jobs:

  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'Release_test'
        token: ${{secrets.YOUR_PAT_SECRET}}
        
  docker_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Directory
        run: |
         echo "test tag"
         
  run_tests:
    needs: checkout
    runs-on: runner_160_1
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      run: |
         chmod +x test.sh  
         ./test.sh
      shell: bash
