name: Docker 
on:
  workflow_dispatch

jobs:
  docker_job:
    runs-on: docker_160
    
    steps:
      - name: Create Directory
        run: |
         touch test_docker/reet.txt
         echo "test"
