name: Docker 
on:
  push:
    branches:
      - main

jobs:
  docker_job:
    runs-on: 
      group: Default
      labels: docker_160
    
    steps:
      - name: Create Directory
        run: mkdir test_docker
